name: Publishing
run-name: publishing on pypi ${{ github.repository }}
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install setuptools and twine
        run: python3 -m pip install --upgrade twine setuptools
      - name: publishing
        run: |
          echo $TAG
          python3 setup.py sdist --new-version "${ $TAG##*/ }"
          twine check dist/*
          twine upload -u $USERNAME -p $PASSWORD dist/*