name: Publishing
run-name: publishing on pypi ${{ github.repository }}
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        with:
          # Utilisez le nom du tag actuel comme version du package
          version: ${{ github.ref }}
