name: Autotag
on:
  push:
    branches:
      - main
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install semver-cli
        run: sudo apt-get install node-semver -y
      - name: Get last tag
        id: last_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - name: Determine new tag version
        id: tag_version
        run: |
          last_tag=$INPUT_LAST_TAG
          message=$(git log --format=%B -n 1 $GITHUB_SHA)
          if [[ $message == *!* ]]; then
            echo "tag=$(semver -i major $last_tag)" >> $GITHUB_OUTPUT
          elif [[ $message == *feat* ]]; then
            echo "tag=$(semver -i minor $last_tag)" >> $GITHUB_OUTPUT
          elif [[ $message == *fix* ]]; then
            echo "tag=$(semver -i patch $last_tag)" >> $GITHUB_OUTPUT
          else
            echo "::set-output name=tag::$last_tag"
            exit 0
          fi
        env:
          INPUT_LAST_TAG: ${{ steps.last_tag.outputs.tag }}
      - name: Create Tag
        if: steps.semver.outputs.tag != ''
        run: git tag ${{ steps.semver.outputs.tag }} -a -m "${{ steps.semver.outputs.tag_message }}" ${{ github.sha }}
      - name: Push changes
        if: steps.semver.outputs.tag != ''
        run: git push origin ${{ steps.semver.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}