name: Publishing
run-name: publishing on pypi ${{ github.repository }}

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@v2
      - name: Installer les dépendances
        run: |
          pip install setuptools twine
      - name: Construire et publier le package
        run: |
          python setup.py sdist bdist_wheel
          twine upload -u $USERNAME -p $PASSWORD dist/*